/* Reiner's Book — dati manovre e pattern NRHA 2026 */
const MAN=[
 {k:'stop',en:'Sliding stop',it:'Arresto in slide',
  mech:'Dal galoppo veloce il cavallo porta i posteriori sotto la massa, piega le anche e scivola sui posteriori mentre gli anteriori continuano a "camminare" (pedalare) liberi. Testa e collo restano rilassati, bocca chiusa.',
  aids:['Siedi: bacino che si arrotonda, peso nei talloni, gambe che si aprono leggermente dal fianco (rilascio).','Voce: "whoa" prima della mano.','Mano: si alza di poco e solo se il cavallo non ha risposto al seat; poi rilascio completo.','Mai buttarsi indietro con il busto: spingi la sella avanti col bacino.'],
  prog:['Al passo: "whoa" + seat + mano, rilascio e backup di 2 passi. Ripeti finché ferma alla voce.','Al jog, poi al lope lento, sempre su terreno buono con skid boots.','Aumenta gradualmente velocità nel rundown (fence): il cavallo che corre verso il muro impara a fermarsi dritto.','Gli stop in gara sono pochi: in allenamento se ne fanno 2–3 per sessione, non 20.'],
  judge:'Merito: distanza e dritto dello slide, anteriori liberi, testa bassa e rilassata. Difetti: posteriori che rimbalzano (bouncing), bocca aperta, storto, anteriori rigidi (propping).'},
 {k:'back',en:'Backup',it:'Indietreggiamento',
  mech:'Il cavallo indietreggia dritto, in diagonale (2 tempi), a testa bassa, per almeno 3 m o fino al centro arena.',
  aids:['Contatto leggero con la mano che si alza di poco verso il busto.','Gambe leggere ai lati per tenere dritto; gamba sinistra se il posteriore va a sinistra.','Rilascio al primo passo, poi ricerca del ritmo.'],
  prog:['Da terra con la capezza: pressione sul naso finché arretra.','In sella da fermo: 1 passo e rilascio; poi 2, poi 5.','Velocità: si aumenta solo quando il backup è dritto e con la testa bassa.'],
  judge:'Merito: velocità, dritto, testa bassa, prontezza. Difetto: lento, storto, bocca aperta, resistenza. Fa parte della manovra dello stop.'},
 {k:'roll',en:'Rollback',it:'Rollback (inversione a 180°)',
  mech:'Stop → il cavallo ruota di 180° sui posteriori (perno sull\'anca interna) → riparte al galoppo sul lead corretto nella direzione opposta, in un unico movimento continuo. "No hesitation" nel pattern.',
  aids:['Stop normale (seat, whoa).','Guarda dove vuoi andare e sposta la mano delle redini nella direzione del rollback: la redine esterna sul collo.','Gamba esterna alla cinghia spinge la spalla; gamba interna leggermente indietro per tenere il posteriore fermo.','Appena il cavallo è girato, gambe e cluck: riparte al lope subito.'],
  prog:['Stop, back di 1 passo, girata di 180° al passo, ripartenza al jog. Il back insegna a stare sui posteriori.','Togli il back: stop → girata → lope. Poi aumenta la velocità del rundown.','Sul muro (fence): il muro ferma il cavallo e aiuta la rotazione.'],
  judge:'Merito: rotazione pulita sui posteriori, ripartenza immediata sul lead giusto. Difetto: esitazione (penalità 2 se freeze), girata sull\'anteriore, over-turn, ripartenza al trotto.'},
 {k:'spin',en:'Spin (turnaround)',it:'Spin (giro sul posteriore)',
  mech:'Il cavallo ruota su un posteriore interno "piantato" (pivot foot) mentre l\'anteriore esterno incrocia davanti all\'interno; 4 giri (o 4¼) a velocità costante o crescente, testa bassa e in linea con il corpo. Fermata precisa sul punto di partenza.',
  aids:['Guarda il punto in cui devi fermarti (il marker o un punto del muro).','Mano: si sposta nella direzione dello spin, redine esterna sul collo. Poca mano: lo spin viene dalla gamba.','Gamba esterna alla cinghia "spinge" la spalla; gamba interna passiva, leggermente avanti.','Corpo: fermo, centrato, non piegato verso l\'interno. Per fermare: "whoa" + seat un quarto prima.'],
  prog:['Al passo: 1 passo di incrocio anteriore, rilascio. Costruisci un quarto di giro alla volta.','Cerca la cadenza: spin lento e corretto prima di quello veloce.','Conta i giri ad alta voce; usa un punto di riferimento fisso per fermarti (over/under spin costano ½–1 punto per ⅛ di giro, 0 score oltre ¼).'],
  judge:'Merito: velocità, cadenza, posteriore fermo, anteriore che incrocia con eleganza, fermata precisa. Difetto: posteriore che si sposta (traveling), testa alta, saltellare, fermata imprecisa.'},
 {k:'circle',en:'Circles (large fast / small slow)',it:'Cerchi',
  mech:'Cerchi rotondi con centro comune al centro arena, sul lead corretto. Large fast = velocità elevata; small slow = raccolto e lento, con differenza evidente. La transizione avviene passando per il centro.',
  aids:['Guarda il punto di uscita, non il collo del cavallo.','Neck rein minimo: il cavallo segue il tuo sguardo e la spalla esterna.','Velocità: gambe e cluck per accelerare; seat e respiro profondo per rallentare (non la mano).','Cambio di dimensione: rallenta 3–4 falcate prima del centro, il cerchio piccolo parte già raccolto.'],
  prog:['Cerchi al jog: rotondi e con un centro chiaro (metti un cono).','Al lope: prima piccolo e lento, poi grande e veloce. Cerca la differenza di velocità netta.','Esercizio "counter-arc" e spalla in dentro per correggere il cavallo che cade dentro (dropping the shoulder).'],
  judge:'Merito: differenza di velocità evidente, cerchio rotondo e simmetrico, controllo con redine lasca. Difetto: cerchi ovali, taglio di dimensione, cambio di velocità sfumato, fuori lead (penalità).'},
 {k:'lead',en:'Flying lead change',it:'Cambio di galoppo in aria',
  mech:'Il cavallo cambia il lead anteriore e posteriore nello stesso tempo di sospensione, al centro arena, senza cambiare velocità o rompere l\'andatura.',
  aids:['Un passo prima del centro raddrizza il cavallo (togli la piega).','Sposta la gamba: quella che era esterna va avanti, la nuova gamba esterna va indietro dietro la cinghia e chiede.','Peso leggermente sulla nuova staffa esterna; mano che accompagna appena sul nuovo lato.','Non anticipare col busto: il cavallo si "sdraia".'],
  prog:['Simple change: lope → 2 passi di jog → lope sull\'altro lead. Insegna il meccanismo.','Counter-canter: galoppo sul lead "sbagliato" in cerchio per costruire equilibrio.','Cambio in aria su una linea dritta, poi sul figure 8. Un cambio corretto alla volta, mai ripetere in serie quando è riuscito.'],
  judge:'Merito: cambio esatto al centro, invisibile, senza cambio di velocità. Difetti: ritardo (½ per passo, 1 per quarto di circle), cambio solo davanti (cross-cantering), aumento di velocità, testa alta.'},
 {k:'run',en:'Rundown / run-around',it:'Rundown (corsa verso lo stop)',
  mech:'Corsa dritta lungo il centro (rundown) o lungo il lato ad almeno 6 m dal muro (run-around), con aumento di velocità progressivo fino allo stop o al rollback oltre il marker.',
  aids:['Parti raccolto, aumenta di una marcia ogni 3–4 falcate.','Guarda il punto oltre il marker in cui fermare: il cavallo va dove guardi.','Mano centrata, cavallo dritto tra le gambe. Prima dello stop: seat.'],
  prog:['Lope lungo il muro a velocità costante, stop, back. Poi aggiungi progressione di velocità.','Insegna al cavallo a non anticipare: a volte non fermi e continui al lope.','Rundown al centro solo quando è dritto sul muro.'],
  judge:'Merito: progressione di velocità controllata, dritto. Difetti: storto, velocità già massima subito (no build-up), cavallo che anticipa e rallenta, fuori lead nel rundown (penalità per quarto).'},
 {k:'hes',en:'Hesitate',it:'Esitazione (pausa di controllo)',
  mech:'Pausa completa da fermo, con il cavallo rilassato, per dimostrare il controllo dopo spin, stop/backup e a fine pattern.',
  aids:['Mano che scende, respiro, cavallo che si "assesta". 2–3 secondi.','Prima della manovra seguente: raccogli, guarda, poi chiedi.'],
  prog:['Insegna al cavallo a stare fermo e rilassato dopo ogni esercizio: è la ricompensa.'],
  judge:'Assente o troppo breve: difetto della manovra. Cavallo che si muove o anticipa: difetto.'},
];

const P=[
{id:'1',name:'Pattern 1',start:'Ingresso al galoppo: il pattern inizia con il rundown.',steps:[
 ['Corri veloce fino al fondo opposto oltre l\'end marker e fai un rollback a sinistra – senza esitazione.','Run at speed to the far end past the end marker, left rollback—no hesitation.',{t:'RU',lane:'C',from:'B',end:'RBL'}],
 ['Corri al fondo opposto oltre l\'end marker e fai un rollback a destra – senza esitazione.','Run to the opposite end past the end marker, right rollback—no hesitation.',{t:'RU',lane:'C',from:'T',end:'RBR'}],
 ['Corri oltre il center marker e fai uno sliding stop. Backup fino al centro o almeno 3 m. Esita.','Run past the center marker, sliding stop. Back up to center or at least 10 ft. Hesitate.',{t:'RU',lane:'C',from:'B',end:'STB'}],
 ['4 spin a destra. Esita.','Complete four spins to the right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['4¼ spin a sinistra, finendo rivolto verso il muro sinistro. Esita.','Four and one-quarter spins to the left, facing the left wall. Hesitate.',{t:'SP',dir:'L',n:4.25}],
 ['Sul galoppo sinistro, 3 cerchi a sinistra: grande veloce, piccolo lento, grande veloce. Cambio di galoppo al centro.','Left lead, three circles left: large fast, small slow, large fast. Change leads at center.',{t:'C',dir:'L',s:'LF,SS,LF'}],
 ['3 cerchi a destra: grande veloce, piccolo lento, grande veloce. Cambio di galoppo al centro.','Three circles right: large fast, small slow, large fast. Change leads at center.',{t:'C',dir:'R',s:'LF,SS,LF'}],
 ['Inizia un cerchio grande a sinistra senza chiuderlo. Corri dritto lungo il lato destro oltre il center marker e fai uno sliding stop ad almeno 6 m dal muro. Esita per dimostrare la fine del pattern.','Begin a large circle left, do not close. Run up the right side past the center marker, sliding stop at least 20 ft from the wall. Hesitate.',{t:'RU',lane:'R',from:'B',end:'ST',open:'L'}]]},
{id:'2',name:'Pattern 2',start:'Passo o jog fino al centro. Inizio al centro, rivolto verso il muro sinistro.',steps:[
 ['Sul galoppo destro, 3 cerchi a destra: piccolo lento, poi due grandi veloci. Cambio al centro.','Right lead, three circles right: small slow, then two large fast. Change leads.',{t:'C',dir:'R',s:'SS,LF,LF'}],
 ['3 cerchi a sinistra: piccolo lento, poi due grandi veloci. Cambio al centro.','Three circles left: small slow, two large fast. Change leads.',{t:'C',dir:'L',s:'SS,LF,LF'}],
 ['Continua sul cerchio a destra; in cima, corri lungo il centro fino al fondo oltre l\'end marker e fai un rollback a destra – senza esitazione.','Continue around the right circle; at the top run down the middle past the end marker, right rollback.',{t:'RU',lane:'C',from:'T',end:'RBR',open:'R'}],
 ['Corri lungo il centro al fondo opposto oltre l\'end marker e fai un rollback a sinistra – senza esitazione.','Run up the middle past the end marker, left rollback.',{t:'RU',lane:'C',from:'B',end:'RBL'}],
 ['Corri oltre il center marker e fai uno sliding stop. Backup fino al centro o almeno 3 m. Esita.','Run past the center marker, sliding stop. Back up. Hesitate.',{t:'RU',lane:'C',from:'T',end:'STB'}],
 ['4 spin a destra. Esita.','Four spins right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['4 spin a sinistra. Esita per dimostrare la fine del pattern.','Four spins left. Hesitate.',{t:'SP',dir:'L',n:4}]]},
{id:'3',name:'Pattern 3',start:'Ingresso al galoppo lungo il lato sinistro.',steps:[
 ['Galoppa dritto lungo il lato sinistro, gira attorno al fondo e, restando ad almeno 6 m dal muro, corri dritto lungo il lato destro oltre il center marker e fai un rollback a sinistra – senza esitazione.','Lope up the left side, circle the top, run down the right side past the center marker, left rollback.',{t:'RU',lane:'R',from:'T',end:'RBL',around:'L'}],
 ['Continua lungo il lato destro, gira attorno al fondo e corri lungo il lato sinistro oltre il center marker: rollback a destra – senza esitazione.','Continue up the right side, circle the top, run down the left side past the center marker, right rollback.',{t:'RU',lane:'L',from:'T',end:'RBR',around:'R'}],
 ['Continua lungo il lato sinistro fino al center marker sul galoppo destro. Porta il cavallo al centro e fai 3 cerchi a destra: due grandi veloci, il terzo piccolo lento. Cambio al centro.','Continue up the left side to the center marker on the right lead. Three circles right: two large fast, third small slow. Change leads.',{t:'C',dir:'R',s:'LF,LF,SS'}],
 ['3 cerchi a sinistra: due grandi veloci, il terzo piccolo lento. Cambio al centro.','Three circles left: two large fast, third small slow. Change leads.',{t:'C',dir:'L',s:'LF,LF,SS'}],
 ['Inizia un cerchio grande a destra senza chiuderlo. Continua lungo il lato sinistro, gira attorno al fondo e corri lungo il lato destro oltre il center marker: sliding stop. Backup almeno 3 m. Esita.','Begin a large circle right, do not close. Up the left side, circle the top, down the right side past the center marker, sliding stop. Back up. Hesitate.',{t:'RU',lane:'R',from:'T',end:'STB',around:'L',open:'R'}],
 ['4 spin a destra. Esita.','Four spins right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['4 spin a sinistra. Esita per dimostrare la fine del pattern.','Four spins left. Hesitate.',{t:'SP',dir:'L',n:4}]]},
{id:'4',name:'Pattern 4',start:'Passo o jog fino al centro. Inizio al centro, rivolto verso il muro sinistro.',steps:[
 ['Sul galoppo destro, 3 cerchi a destra: due grandi veloci, il terzo piccolo lento. Stop al centro. Esita.','Right lead, three circles right: two large fast, third small slow. Stop at center. Hesitate.',{t:'C',dir:'R',s:'LF,LF,SS',stop:1}],
 ['4 spin a destra. Esita.','Four spins right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['Sul galoppo sinistro, 3 cerchi a sinistra: due grandi veloci, il terzo piccolo lento. Stop al centro. Esita.','Left lead, three circles left: two large fast, third small slow. Stop at center. Hesitate.',{t:'C',dir:'L',s:'LF,LF,SS',stop:1}],
 ['4 spin a sinistra. Esita.','Four spins left. Hesitate.',{t:'SP',dir:'L',n:4}],
 ['Sul galoppo destro, un cerchio grande veloce a destra, cambio al centro, un cerchio grande veloce a sinistra, cambio al centro (figure 8).','Right lead, large fast circle right, change leads, large fast circle left, change leads (Figure 8).',{t:'F8',dir:'R'}],
 ['Continua sul cerchio a destra; in cima corri lungo il centro fino al fondo oltre l\'end marker: rollback a destra – senza esitazione.','Continue around the right circle; at the top run down the middle past the end marker, right rollback.',{t:'RU',lane:'C',from:'T',end:'RBR',open:'R'}],
 ['Corri lungo il centro al fondo opposto oltre l\'end marker: rollback a sinistra – senza esitazione.','Run up the middle past the end marker, left rollback.',{t:'RU',lane:'C',from:'B',end:'RBL'}],
 ['Corri oltre il center marker: sliding stop. Backup fino al centro o almeno 3 m. Esita per dimostrare la fine del pattern.','Run past the center marker, sliding stop. Back up. Hesitate.',{t:'RU',lane:'C',from:'T',end:'STB'}]]},
{id:'5',name:'Pattern 5',start:'Passo o jog fino al centro. Inizio al centro, rivolto verso il muro sinistro.',steps:[
 ['Sul galoppo sinistro, 3 cerchi a sinistra: due grandi veloci, il terzo piccolo lento. Stop al centro. Esita.','Left lead, three circles left: two large fast, third small slow. Stop at center. Hesitate.',{t:'C',dir:'L',s:'LF,LF,SS',stop:1}],
 ['4 spin a sinistra. Esita.','Four spins left. Hesitate.',{t:'SP',dir:'L',n:4}],
 ['Sul galoppo destro, 3 cerchi a destra: due grandi veloci, il terzo piccolo lento. Stop al centro. Esita.','Right lead, three circles right: two large fast, third small slow. Stop at center. Hesitate.',{t:'C',dir:'R',s:'LF,LF,SS',stop:1}],
 ['4 spin a destra. Esita.','Four spins right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['Sul galoppo sinistro, un cerchio grande veloce a sinistra, cambio al centro, un cerchio grande veloce a destra, cambio al centro (figure 8).','Left lead figure 8: large fast left, change, large fast right, change.',{t:'F8',dir:'L'}],
 ['Continua sul cerchio a sinistra senza chiuderlo. Corri lungo il lato destro oltre il center marker: rollback a destra ad almeno 6 m dal muro – senza esitazione.','Continue around the left circle, do not close. Run up the right side past the center marker, right rollback at least 20 ft from wall.',{t:'RU',lane:'R',from:'B',end:'RBR',open:'L'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato sinistro oltre il center marker: rollback a sinistra ad almeno 6 m dal muro – senza esitazione.','Continue around previous circle, do not close. Run up the left side past the center marker, left rollback.',{t:'RU',lane:'L',from:'B',end:'RBL',open:'R'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato destro oltre il center marker: sliding stop ad almeno 6 m dal muro. Backup almeno 3 m. Esita per dimostrare la fine del pattern.','Continue back around, do not close. Run up the right side past the center marker, sliding stop. Back up at least 10 ft. Hesitate.',{t:'RU',lane:'R',from:'B',end:'STB',open:'L'}]]},
{id:'6',name:'Pattern 6',start:'Passo o jog fino al centro. Inizio al centro, rivolto verso il muro sinistro.',steps:[
 ['4 spin a destra. Esita.','Four spins right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['4 spin a sinistra. Esita.','Four spins left. Hesitate.',{t:'SP',dir:'L',n:4}],
 ['Sul galoppo sinistro, 3 cerchi a sinistra: due grandi veloci, il terzo piccolo lento. Cambio al centro.','Left lead, three circles left: two large fast, third small slow. Change leads.',{t:'C',dir:'L',s:'LF,LF,SS'}],
 ['3 cerchi a destra: due grandi veloci, il terzo piccolo lento. Cambio al centro.','Three circles right: two large fast, third small slow. Change leads.',{t:'C',dir:'R',s:'LF,LF,SS'}],
 ['Inizia un cerchio grande a sinistra senza chiuderlo. Corri lungo il lato destro oltre il center marker: rollback a destra ad almeno 6 m dal muro – senza esitazione.','Begin a large circle left, do not close. Run up the right side past the center marker, right rollback.',{t:'RU',lane:'R',from:'B',end:'RBR',open:'L'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato sinistro oltre il center marker: rollback a sinistra ad almeno 6 m dal muro – senza esitazione.','Continue back around, do not close. Run up the left side past the center marker, left rollback.',{t:'RU',lane:'L',from:'B',end:'RBL',open:'R'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato destro oltre il center marker: sliding stop ad almeno 6 m dal muro. Backup almeno 3 m. Esita per dimostrare la fine del pattern.','Continue back around, do not close. Run up the right side, sliding stop. Back up. Hesitate.',{t:'RU',lane:'R',from:'B',end:'STB',open:'L'}]]},
{id:'7',name:'Pattern 7',start:'Ingresso al galoppo: il pattern inizia con il rundown.',steps:[
 ['Corri veloce fino al fondo opposto oltre l\'end marker: rollback a sinistra – senza esitazione.','Run at speed to the far end past the end marker, left rollback.',{t:'RU',lane:'C',from:'B',end:'RBL'}],
 ['Corri al fondo opposto oltre l\'end marker: rollback a destra – senza esitazione.','Run to the opposite end past the end marker, right rollback.',{t:'RU',lane:'C',from:'T',end:'RBR'}],
 ['Corri oltre il center marker: sliding stop. Backup fino al centro o almeno 3 m. Esita.','Run past the center marker, sliding stop. Back up. Hesitate.',{t:'RU',lane:'C',from:'B',end:'STB'}],
 ['4 spin a destra. Esita.','Four spins right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['4¼ spin a sinistra, finendo rivolto verso il muro sinistro. Esita.','Four and one-quarter spins left, facing the left wall. Hesitate.',{t:'SP',dir:'L',n:4.25}],
 ['Sul galoppo destro, 3 cerchi a destra: due grandi veloci, il terzo piccolo lento. Cambio al centro.','Right lead, three circles right: two large fast, third small slow. Change leads.',{t:'C',dir:'R',s:'LF,LF,SS'}],
 ['3 cerchi a sinistra: due grandi veloci, il terzo piccolo lento. Cambio al centro.','Three circles left: two large fast, third small slow. Change leads.',{t:'C',dir:'L',s:'LF,LF,SS'}],
 ['Inizia un cerchio grande a destra senza chiuderlo. Corri dritto lungo il lato destro oltre il center marker: sliding stop ad almeno 6 m dal muro. Esita per dimostrare la fine del pattern.','Begin a large circle right, do not close. Run down the right side past the center marker, sliding stop. Hesitate.',{t:'RU',lane:'R',from:'T',end:'ST',open:'R'}]]},
{id:'8',name:'Pattern 8',start:'Passo o jog fino al centro. Inizio al centro, rivolto verso il muro sinistro.',steps:[
 ['4 spin a sinistra. Esita.','Four spins left. Hesitate.',{t:'SP',dir:'L',n:4}],
 ['4 spin a destra. Esita.','Four spins right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['Sul galoppo destro, 3 cerchi a destra: grande veloce, piccolo lento, grande veloce. Cambio al centro.','Right lead, three circles right: large fast, small slow, large fast. Change leads.',{t:'C',dir:'R',s:'LF,SS,LF'}],
 ['3 cerchi a sinistra: grande veloce, piccolo lento, grande veloce. Cambio al centro.','Three circles left: large fast, small slow, large fast. Change leads.',{t:'C',dir:'L',s:'LF,SS,LF'}],
 ['Inizia un cerchio grande a destra senza chiuderlo. Corri dritto lungo il lato destro oltre il center marker: rollback a sinistra ad almeno 6 m dal muro – senza esitazione.','Begin a large circle right, do not close. Run down the right side past the center marker, left rollback.',{t:'RU',lane:'R',from:'T',end:'RBL',open:'R'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato sinistro oltre il center marker: rollback a destra ad almeno 6 m dal muro – senza esitazione.','Continue back around, do not close. Run down the left side past the center marker, right rollback.',{t:'RU',lane:'L',from:'T',end:'RBR',open:'L'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato destro oltre il center marker: sliding stop ad almeno 6 m dal muro. Backup almeno 3 m. Esita per dimostrare la fine del pattern.','Continue back around, do not close. Run down the right side, sliding stop. Back up. Hesitate.',{t:'RU',lane:'R',from:'T',end:'STB',open:'R'}]]},
{id:'9',name:'Pattern 9',start:'Ingresso al galoppo: il pattern inizia con il rundown.',steps:[
 ['Corri oltre il center marker: sliding stop. Backup fino al centro o almeno 3 m. Esita.','Run past the center marker, sliding stop. Back up. Hesitate.',{t:'RU',lane:'C',from:'B',end:'STB'}],
 ['4 spin a destra. Esita.','Four spins right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['4¼ spin a sinistra, finendo rivolto verso il muro sinistro. Esita.','Four and one-quarter spins left, facing the left wall. Hesitate.',{t:'SP',dir:'L',n:4.25}],
 ['Sul galoppo sinistro, 3 cerchi a sinistra: piccolo lento, poi due grandi veloci. Cambio al centro.','Left lead, three circles left: small slow, two large fast. Change leads.',{t:'C',dir:'L',s:'SS,LF,LF'}],
 ['3 cerchi a destra: piccolo lento, poi due grandi veloci. Cambio al centro.','Three circles right: small slow, two large fast. Change leads.',{t:'C',dir:'R',s:'SS,LF,LF'}],
 ['Inizia un cerchio grande a sinistra senza chiuderlo. Corri lungo il lato destro oltre il center marker: rollback a destra ad almeno 6 m dal muro – senza esitazione.','Begin a large circle left, do not close. Run up the right side past the center marker, right rollback.',{t:'RU',lane:'R',from:'B',end:'RBR',open:'L'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato sinistro oltre il center marker: rollback a sinistra ad almeno 6 m dal muro – senza esitazione.','Continue back around, do not close. Run up the left side, left rollback.',{t:'RU',lane:'L',from:'B',end:'RBL',open:'R'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato destro oltre il center marker: sliding stop ad almeno 6 m dal muro. Esita per dimostrare la fine del pattern.','Continue back around, do not close. Run up the right side, sliding stop. Hesitate.',{t:'RU',lane:'R',from:'B',end:'ST',open:'L'}]]},
{id:'10',name:'Pattern 10',start:'Ingresso al galoppo: il pattern inizia con il rundown.',steps:[
 ['Corri oltre il center marker: sliding stop. Backup fino al centro o almeno 3 m. Esita.','Run past the center marker, sliding stop. Back up. Hesitate.',{t:'RU',lane:'C',from:'B',end:'STB'}],
 ['4 spin a destra. Esita.','Four spins right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['4¼ spin a sinistra, finendo rivolto verso il muro sinistro. Esita.','Four and one-quarter spins left. Hesitate.',{t:'SP',dir:'L',n:4.25}],
 ['Sul galoppo destro, 3 cerchi a destra: due grandi veloci, il terzo piccolo lento. Cambio al centro.','Right lead, three circles right: two large fast, third small slow. Change leads.',{t:'C',dir:'R',s:'LF,LF,SS'}],
 ['3 cerchi a sinistra: piccolo lento, poi due grandi veloci. Cambio al centro.','Three circles left: small slow, two large fast. Change leads.',{t:'C',dir:'L',s:'SS,LF,LF'}],
 ['Inizia un cerchio grande a destra senza chiuderlo. Corri lungo il lato destro oltre il center marker: rollback a sinistra ad almeno 6 m dal muro – senza esitazione.','Begin a large circle right, do not close. Run down the right side past the center marker, left rollback.',{t:'RU',lane:'R',from:'T',end:'RBL',open:'R'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato sinistro oltre il centro: rollback a destra ad almeno 6 m dal muro – senza esitazione.','Continue back around, do not close. Run down the left side past the center, right rollback.',{t:'RU',lane:'L',from:'T',end:'RBR',open:'L'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato destro oltre il center marker: sliding stop ad almeno 6 m dal muro. Esita per dimostrare la fine del pattern.','Continue back around, do not close. Run down the right side, sliding stop. Hesitate.',{t:'RU',lane:'R',from:'T',end:'ST',open:'R'}]]},
{id:'11',name:'Pattern 11',start:'Jog obbligatorio fino al centro. Inizio al centro, rivolto verso il muro sinistro.',steps:[
 ['4 spin a sinistra. Esita.','Four spins left. Hesitate.',{t:'SP',dir:'L',n:4}],
 ['4 spin a destra. Esita.','Four spins right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['Sul galoppo destro, 3 cerchi a destra: piccolo lento, poi due grandi veloci. Cambio al centro.','Right lead, three circles right: small slow, two large fast. Change leads.',{t:'C',dir:'R',s:'SS,LF,LF'}],
 ['3 cerchi a sinistra: piccolo lento, poi due grandi veloci. Cambio al centro.','Three circles left: small slow, two large fast. Change leads.',{t:'C',dir:'L',s:'SS,LF,LF'}],
 ['Inizia un cerchio grande a destra senza chiuderlo. Corri lungo il centro oltre l\'end marker: rollback a destra – senza esitazione.','Begin a large circle right, do not close. Run down the center past the end marker, right rollback.',{t:'RU',lane:'C',from:'T',end:'RBR',open:'R'}],
 ['Corri lungo il centro al fondo opposto oltre l\'end marker: rollback a sinistra – senza esitazione.','Run up the middle past the end marker, left rollback.',{t:'RU',lane:'C',from:'B',end:'RBL'}],
 ['Corri oltre il center marker: sliding stop. Backup fino al centro o almeno 3 m. Esita per dimostrare la fine del pattern.','Run past the center marker, sliding stop. Back up. Hesitate.',{t:'RU',lane:'C',from:'T',end:'STB'}]]},
{id:'12',name:'Pattern 12',start:'Ingresso al galoppo: il pattern inizia con il rundown.',steps:[
 ['Corri oltre il center marker: sliding stop. Backup fino al centro o almeno 3 m. Esita.','Run past the center marker, sliding stop. Back up. Hesitate.',{t:'RU',lane:'C',from:'B',end:'STB'}],
 ['4 spin a destra. Esita.','Four spins right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['4¼ spin a sinistra, finendo rivolto verso il muro sinistro. Esita.','Four and one-quarter spins left. Hesitate.',{t:'SP',dir:'L',n:4.25}],
 ['Sul galoppo sinistro, 3 cerchi a sinistra: due grandi veloci, il terzo piccolo lento. Cambio al centro.','Left lead, three circles left: two large fast, third small slow. Change leads.',{t:'C',dir:'L',s:'LF,LF,SS'}],
 ['3 cerchi a destra: due grandi veloci, il terzo piccolo lento. Cambio al centro.','Three circles right: two large fast, third small slow. Change leads.',{t:'C',dir:'R',s:'LF,LF,SS'}],
 ['Inizia un cerchio grande a sinistra senza chiuderlo. Corri lungo il lato destro oltre il center marker: rollback a destra ad almeno 6 m dal muro – senza esitazione.','Begin a large circle left, do not close. Run up the right side, right rollback.',{t:'RU',lane:'R',from:'B',end:'RBR',open:'L'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato sinistro oltre il center marker: rollback a sinistra ad almeno 6 m dal muro – senza esitazione.','Continue back around, do not close. Run up the left side, left rollback.',{t:'RU',lane:'L',from:'B',end:'RBL',open:'R'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato destro oltre il center marker: sliding stop ad almeno 6 m dal muro. Esita per dimostrare la fine del pattern.','Continue back around, do not close. Run up the right side, sliding stop. Hesitate.',{t:'RU',lane:'R',from:'B',end:'ST',open:'L'}]]},
{id:'13',name:'Pattern 13',start:'Passo o jog fino al centro. Inizio al centro, rivolto verso il muro sinistro.',steps:[
 ['Sul galoppo sinistro, 2 cerchi a sinistra: grande veloce, poi piccolo lento. Stop al centro. Esita.','Left lead, two circles left: large fast, small slow. Stop at center. Hesitate.',{t:'C',dir:'L',s:'LF,SS',stop:1}],
 ['4 spin a sinistra. Esita.','Four spins left. Hesitate.',{t:'SP',dir:'L',n:4}],
 ['Sul galoppo destro, 2 cerchi a destra: grande veloce, poi piccolo lento. Stop al centro. Esita.','Right lead, two circles right: large fast, small slow. Stop at center. Hesitate.',{t:'C',dir:'R',s:'LF,SS',stop:1}],
 ['4 spin a destra. Esita.','Four spins right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['Sul galoppo sinistro, figure 8: cerchio grande veloce a sinistra, cambio al centro, cerchio grande veloce a destra, cambio al centro.','Left lead figure 8: large fast left, change, large fast right, change.',{t:'F8',dir:'L'}],
 ['Continua sul cerchio a sinistra senza chiuderlo. Corri lungo il lato destro oltre il center marker: rollback a destra ad almeno 6 m dal muro – senza esitazione.','Continue around the left circle, do not close. Run up the right side, right rollback.',{t:'RU',lane:'R',from:'B',end:'RBR',open:'L'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato sinistro oltre il center marker: rollback a sinistra ad almeno 6 m dal muro – senza esitazione.','Continue around, do not close. Run up the left side, left rollback.',{t:'RU',lane:'L',from:'B',end:'RBL',open:'R'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato destro oltre il center marker: sliding stop ad almeno 6 m dal muro. Backup almeno 3 m. Esita per dimostrare la fine del pattern.','Continue back around, do not close. Run up the right side, sliding stop. Back up. Hesitate.',{t:'RU',lane:'R',from:'B',end:'STB',open:'L'}]]},
{id:'14',name:'Pattern 14',start:'Passo o jog fino al centro. Inizio al centro, rivolto verso il muro sinistro. (Inverso del 6)',steps:[
 ['4 spin a sinistra. Esita.','Four spins left. Hesitate.',{t:'SP',dir:'L',n:4}],
 ['4 spin a destra. Esita.','Four spins right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['Sul galoppo destro, 3 cerchi a destra: due grandi veloci, il terzo piccolo lento. Cambio al centro.','Right lead, three circles right: two large fast, third small slow. Change leads.',{t:'C',dir:'R',s:'LF,LF,SS'}],
 ['3 cerchi a sinistra: due grandi veloci, il terzo piccolo lento. Cambio al centro.','Three circles left: two large fast, third small slow. Change leads.',{t:'C',dir:'L',s:'LF,LF,SS'}],
 ['Inizia un cerchio grande a destra senza chiuderlo. Corri lungo il lato destro oltre il center marker: rollback a sinistra ad almeno 6 m dal muro – senza esitazione.','Begin a large circle right, do not close. Run up the right side past the center marker, left rollback.',{t:'RU',lane:'R',from:'B',end:'RBL',open:'R'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato sinistro oltre il center marker: rollback a destra ad almeno 6 m dal muro – senza esitazione.','Continue back around, do not close. Run up the left side, right rollback.',{t:'RU',lane:'L',from:'B',end:'RBR',open:'L'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato destro oltre il center marker: sliding stop ad almeno 6 m dal muro. Backup almeno 3 m. Esita per dimostrare la fine del pattern.','Continue back around, do not close. Run up the right side, sliding stop. Back up. Hesitate.',{t:'RU',lane:'R',from:'B',end:'STB',open:'R'}]]},
{id:'15',name:'Pattern 15',start:'Passo o jog fino al centro. Inizio al centro, rivolto verso il muro sinistro. (Inverso dell\'8)',steps:[
 ['4 spin a destra. Esita.','Four spins right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['4 spin a sinistra. Esita.','Four spins left. Hesitate.',{t:'SP',dir:'L',n:4}],
 ['Sul galoppo sinistro, 3 cerchi a sinistra: grande veloce, piccolo lento, grande veloce. Cambio al centro.','Left lead, three circles left: large fast, small slow, large fast. Change leads.',{t:'C',dir:'L',s:'LF,SS,LF'}],
 ['3 cerchi a destra: grande veloce, piccolo lento, grande veloce. Cambio al centro.','Three circles right: large fast, small slow, large fast. Change leads.',{t:'C',dir:'R',s:'LF,SS,LF'}],
 ['Inizia un cerchio grande a sinistra senza chiuderlo. Corri dritto lungo il lato destro oltre il center marker: rollback a destra ad almeno 6 m dal muro – senza esitazione.','Begin a large circle left, do not close. Run down the right side past the center marker, right rollback.',{t:'RU',lane:'R',from:'T',end:'RBR',open:'L'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato sinistro oltre il center marker: rollback a sinistra ad almeno 6 m dal muro – senza esitazione.','Continue back around, do not close. Run down the left side, left rollback.',{t:'RU',lane:'L',from:'T',end:'RBL',open:'R'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato destro oltre il center marker: sliding stop ad almeno 6 m dal muro. Backup almeno 3 m. Esita per dimostrare la fine del pattern.','Continue back around, do not close. Run down the right side, sliding stop. Back up. Hesitate.',{t:'RU',lane:'R',from:'T',end:'STB',open:'L'}]]},
{id:'16',name:'Pattern 16',start:'Ingresso al galoppo: il pattern inizia con il rundown. (Inverso del 12)',steps:[
 ['Corri oltre il center marker: sliding stop. Backup fino al centro o almeno 3 m. Esita.','Run past the center marker, sliding stop. Back up. Hesitate.',{t:'RU',lane:'C',from:'B',end:'STB'}],
 ['4 spin a sinistra. Esita.','Four spins left. Hesitate.',{t:'SP',dir:'L',n:4}],
 ['4¼ spin a destra, finendo rivolto verso il muro destro. Esita.','Four and one-quarter spins right, facing the right wall. Hesitate.',{t:'SP',dir:'R',n:4.25}],
 ['Sul galoppo destro, 3 cerchi a destra: due grandi veloci, il terzo piccolo lento. Cambio al centro.','Right lead, three circles right: two large fast, third small slow. Change leads.',{t:'C',dir:'R',s:'LF,LF,SS'}],
 ['3 cerchi a sinistra: due grandi veloci, il terzo piccolo lento. Cambio al centro.','Three circles left: two large fast, third small slow. Change leads.',{t:'C',dir:'L',s:'LF,LF,SS'}],
 ['Inizia un cerchio grande a destra senza chiuderlo. Corri lungo il lato sinistro oltre il center marker: rollback a sinistra ad almeno 6 m dal muro – senza esitazione.','Begin a large circle right, do not close. Run up the left side past the center marker, left rollback.',{t:'RU',lane:'L',from:'B',end:'RBL',open:'R'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato destro oltre il center marker: rollback a destra ad almeno 6 m dal muro – senza esitazione.','Continue back around, do not close. Run up the right side, right rollback.',{t:'RU',lane:'R',from:'B',end:'RBR',open:'L'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato sinistro oltre il center marker: sliding stop ad almeno 6 m dal muro. Esita per dimostrare la fine del pattern.','Continue back around, do not close. Run up the left side, sliding stop. Hesitate.',{t:'RU',lane:'L',from:'B',end:'ST',open:'R'}]]},
{id:'17',name:'Pattern 17',start:'Ingresso sul galoppo sinistro: si arriva al centro senza fermarsi né rompere l\'andatura, rivolti verso il muro sinistro.',steps:[
 ['Continuando sul galoppo sinistro, 2 cerchi a sinistra: grande veloce, poi piccolo lento. Stop al centro. Esita.','Continue on the left lead, two circles left: large fast, small slow. Stop at center. Hesitate.',{t:'C',dir:'L',s:'LF,SS',stop:1}],
 ['4 spin a sinistra. Esita.','Four spins left. Hesitate.',{t:'SP',dir:'L',n:4}],
 ['Sul galoppo destro, 2 cerchi a destra: grande veloce, poi piccolo lento. Stop al centro. Esita.','Right lead, two circles right: large fast, small slow. Stop at center. Hesitate.',{t:'C',dir:'R',s:'LF,SS',stop:1}],
 ['4 spin a destra. Esita.','Four spins right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['Sul galoppo sinistro, figure 8: grande veloce a sinistra, cambio, grande veloce a destra, cambio.','Left lead figure 8.',{t:'F8',dir:'L'}],
 ['Continua sul cerchio a sinistra senza chiuderlo. Corri lungo il lato destro oltre il center marker: rollback a destra ad almeno 6 m dal muro – senza esitazione.','Continue around the left circle, do not close. Run up the right side, right rollback.',{t:'RU',lane:'R',from:'B',end:'RBR',open:'L'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato sinistro oltre il center marker: rollback a sinistra ad almeno 6 m dal muro – senza esitazione.','Continue around, do not close. Run up the left side, left rollback.',{t:'RU',lane:'L',from:'B',end:'RBL',open:'R'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato destro oltre il center marker: sliding stop ad almeno 6 m dal muro. Backup almeno 3 m. Esita per dimostrare la fine del pattern.','Continue back around, do not close. Run up the right side, sliding stop. Back up. Hesitate.',{t:'RU',lane:'R',from:'B',end:'STB',open:'L'}]]},
{id:'18',name:'Pattern 18',start:'Ingresso sul galoppo sinistro: si arriva al centro senza fermarsi né rompere l\'andatura, rivolti verso il muro sinistro.',steps:[
 ['Continuando sul galoppo sinistro, 3 cerchi a sinistra: due grandi veloci, il terzo piccolo lento. Stop al centro. Esita.','Continue on the left lead, three circles left: two large fast, third small slow. Stop at center. Hesitate.',{t:'C',dir:'L',s:'LF,LF,SS',stop:1}],
 ['4 spin a sinistra. Esita.','Four spins left. Hesitate.',{t:'SP',dir:'L',n:4}],
 ['Sul galoppo destro, 3 cerchi a destra: due grandi veloci, il terzo piccolo lento. Stop al centro. Esita.','Right lead, three circles right: two large fast, third small slow. Stop at center. Hesitate.',{t:'C',dir:'R',s:'LF,LF,SS',stop:1}],
 ['4 spin a destra. Esita.','Four spins right. Hesitate.',{t:'SP',dir:'R',n:4}],
 ['Sul galoppo sinistro, figure 8: grande veloce a sinistra, cambio, grande veloce a destra, cambio.','Left lead figure 8.',{t:'F8',dir:'L'}],
 ['Continua sul cerchio a sinistra senza chiuderlo. Corri lungo il lato destro oltre il center marker: rollback a destra ad almeno 6 m dal muro – senza esitazione.','Continue around the left circle, do not close. Run up the right side, right rollback.',{t:'RU',lane:'R',from:'B',end:'RBR',open:'L'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato sinistro oltre il center marker: rollback a sinistra ad almeno 6 m dal muro – senza esitazione.','Continue around, do not close. Run up the left side, left rollback.',{t:'RU',lane:'L',from:'B',end:'RBL',open:'R'}],
 ['Continua sul cerchio precedente senza chiuderlo. Corri lungo il lato destro oltre il center marker: sliding stop ad almeno 6 m dal muro. Backup almeno 3 m. Esita per dimostrare la fine del pattern.','Continue back around, do not close. Run up the right side, sliding stop. Back up. Hesitate.',{t:'RU',lane:'R',from:'B',end:'STB',open:'L'}]]},
{id:'A',name:'Pattern A',start:'Solo Youth 10 &amp; Under Short Stirrup e Para-Reining. Passo o jog fino al centro, rivolto verso il muro sinistro.',steps:[
 ['Sul galoppo sinistro, 2 cerchi a sinistra. Stop al centro. Esita.','Left lead, two circles left. Stop at center. Hesitate.',{t:'C',dir:'L',s:'LF,LF',stop:1}],
 ['2 spin a sinistra. Esita.','Two spins left. Hesitate.',{t:'SP',dir:'L',n:2}],
 ['Sul galoppo destro, 2 cerchi a destra. Stop al centro. Esita.','Right lead, two circles right. Stop at center. Hesitate.',{t:'C',dir:'R',s:'LF,LF',stop:1}],
 ['2 spin a destra. Esita.','Two spins right. Hesitate.',{t:'SP',dir:'R',n:2}],
 ['Sul galoppo sinistro, gira attorno al fondo, corri lungo il lato destro oltre il center marker, stop e rollback a destra.','Left lead, around the end of the arena, run down the right side past the center marker, stop and roll back right.',{t:'RU',lane:'R',from:'T',end:'RBR',open:'L'}],
 ['Continua attorno al fondo e corri lungo il lato sinistro oltre il center marker. Stop. Backup. Esita per dimostrare la fine del pattern.','Continue around the end, run down the left side past the center marker. Stop. Back up. Hesitate.',{t:'RU',lane:'L',from:'T',end:'STB',around:'R'}]]},
{id:'B',name:'Pattern B',start:'Solo Youth 10 &amp; Under Short Stirrup e Para-Reining. Ingresso al galoppo lungo il lato destro.',steps:[
 ['Galoppa dritto lungo il lato destro, gira attorno al fondo e corri lungo il lato sinistro oltre il center marker: rollback a destra – senza esitazione.','Lope up the right side, circle the top, run down the left side past the center marker, right rollback.',{t:'RU',lane:'L',from:'T',end:'RBR',around:'R'}],
 ['Continua lungo il lato sinistro, gira attorno al fondo e corri lungo il lato destro oltre il center marker: rollback a sinistra – senza esitazione.','Continue up the left side, circle the top, run down the right side, left rollback.',{t:'RU',lane:'R',from:'T',end:'RBL',around:'L'}],
 ['Continua lungo il lato destro fino al center marker sul galoppo sinistro; 2 cerchi a sinistra: grande veloce e piccolo lento. Stop al centro. Esita.','Continue up the right side to the center marker on the left lead; two circles left, one large fast and one small slow. Stop at center. Hesitate.',{t:'C',dir:'L',s:'LF,SS',stop:1}],
 ['3 spin a sinistra. Esita.','Three spins left. Hesitate.',{t:'SP',dir:'L',n:3}],
 ['2 cerchi a destra: grande veloce e piccolo lento. Stop al centro. Esita.','Two circles right, one large fast and one small slow. Stop at center. Hesitate.',{t:'C',dir:'R',s:'LF,SS',stop:1}],
 ['3 spin a destra. Esita.','Three spins right. Hesitate.',{t:'SP',dir:'R',n:3}],
 ['Inizia un cerchio grande a sinistra senza chiuderlo. Continua lungo il centro oltre il center marker: sliding stop. Backup almeno 3 m. Esita per dimostrare la fine del pattern.','Begin a large circle left, do not close. Continue up the center past the center marker, sliding stop. Back up at least 10 ft. Hesitate.',{t:'RU',lane:'C',from:'B',end:'STB',open:'L'}]]},
];

